const actors = [
  {
    adult: false,
    gender: 2,
    id: 12799,
    known_for_department: "Acting",
    name: "Jeremy Piven",
    original_name: "Jeremy Piven",
    popularity: 268.871,
    profile_path: "/pqdR8zqAWF87chGYlbdYr0YfC7g.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        id: 920,
        title: "Cars",
        original_language: "en",
        original_title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster_path: "/abW5AzHDaIK1n9C36VdAeOwORRA.jpg",
        media_type: "movie",
        genre_ids: [16, 12, 35, 10751],
        popularity: 61.698,
        release_date: "2006-06-08",
        video: false,
        vote_average: 6.944,
        vote_count: 13073,
      },
      {
        adult: false,
        backdrop_path: "/gU7EMTMV3d2ykb9630PAwLSvtSz.jpg",
        id: 9778,
        title: "Serendipity",
        original_language: "en",
        original_title: "Serendipity",
        overview:
          "Although strangers Sara and Jonathan are both already in relationships, they realize they have genuine chemistry after a chance encounter – but part company soon after. Years later, they each yearn to reunite, despite being destined for the altar. But to give true love a chance, they have to find one another again.",
        poster_path: "/srCE5lEIjVEG5eqWg9JcjZCK1aQ.jpg",
        media_type: "movie",
        genre_ids: [35, 10749, 18],
        popularity: 37.25,
        release_date: "2001-10-05",
        video: false,
        vote_average: 6.908,
        vote_count: 1772,
      },
      {
        adult: false,
        backdrop_path: "/6bNQuKFJIamipvYclG4MEbDSLM5.jpg",
        id: 93837,
        title: "So Undercover",
        original_language: "en",
        original_title: "So Undercover",
        overview:
          "When the FBI hires her to go undercover at a college sorority, Molly Morris (Miley Cyrus) must transform herself from a tough, streetwise private investigator to a refined, sophisticated university girl to help protect the daughter of a one-time Mobster. With several suspects on her list, Molly unexpectedly discovers that not everyone is who they appear to be, including herself.",
        poster_path: "/abR6e0FaWwwcEJEM4PY5VvjwBr1.jpg",
        media_type: "movie",
        genre_ids: [28, 35],
        popularity: 40.039,
        release_date: "2012-12-06",
        video: false,
        vote_average: 6.159,
        vote_count: 1082,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 6161,
    known_for_department: "Acting",
    name: "Jennifer Connelly",
    original_name: "Jennifer Connelly",
    popularity: 169.893,
    profile_path: "/3oYDftEbM3YgBiHYcbbIPRNZrTL.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/zbpZOYrRCxEF8lFT5JC8XodEggC.jpg",
        id: 453,
        title: "A Beautiful Mind",
        original_language: "en",
        original_title: "A Beautiful Mind",
        overview:
          "John Nash is a brilliant but asocial mathematician fighting schizophrenia. After he accepts secret work in cryptography, his life takes a turn for the nightmarish.",
        poster_path: "/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg",
        media_type: "movie",
        genre_ids: [18, 10749],
        popularity: 122.268,
        release_date: "2001-12-14",
        video: false,
        vote_average: 7.855,
        vote_count: 9593,
      },
      {
        adult: false,
        backdrop_path: "/s5R6kTMfOxkGit96A8lqcDL4uVk.jpg",
        id: 641,
        title: "Requiem for a Dream",
        original_language: "en",
        original_title: "Requiem for a Dream",
        overview:
          "The hopes and dreams of four ambitious people are shattered when their drug addictions begin spiraling out of control. A look into addiction and how it overcomes the mind and body.",
        poster_path: "/nOd6vjEmzCT0k4VYqsA2hwyi87C.jpg",
        media_type: "movie",
        genre_ids: [80, 18],
        popularity: 27.858,
        release_date: "2000-10-06",
        video: false,
        vote_average: 8.025,
        vote_count: 9302,
      },
      {
        adult: false,
        backdrop_path: "/5z75Q6nqgwgYfpMB9fVHQcw9gMz.jpg",
        id: 86834,
        title: "Noah",
        original_language: "en",
        original_title: "Noah",
        overview:
          "A man who suffers visions of an apocalyptic deluge takes measures to protect his family from the coming flood.",
        poster_path: "/trtD17IqSWV9Nbn4OILztc9GuCX.jpg",
        media_type: "movie",
        genre_ids: [18, 12],
        popularity: 46.625,
        release_date: "2014-03-07",
        video: false,
        vote_average: 5.658,
        vote_count: 5902,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 2359226,
    known_for_department: "Acting",
    name: "Aya Asahina",
    original_name: "Aya Asahina",
    popularity: 156.466,
    profile_path: "/zF3la0KvayUV3uACYPiBgCRIQcI.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/bKxiLRPVWe2nZXCzt6JPr5HNWYm.jpg",
        id: 110316,
        name: "Alice in Borderland",
        original_language: "ja",
        original_name: "今際の国のアリス",
        overview:
          "With his two friends, a video-game-obsessed young man finds himself in a strange version of Tokyo where they must compete in dangerous games to win.",
        poster_path: "/20mOwAAPwZ1vLQkw0fvuQHiG7bO.jpg",
        media_type: "tv",
        genre_ids: [18, 9648, 10759],
        popularity: 386.314,
        first_air_date: "2020-12-10",
        vote_average: 8.187,
        vote_count: 1723,
        origin_country: ["JP"],
      },
      {
        adult: false,
        backdrop_path: null,
        id: 677602,
        title: "Grand Blue",
        original_language: "ja",
        original_title: "ぐらんぶる",
        overview:
          "Iori’s only dream is to go to college on a remote island—but when he gets roped into the school’s debaucherous, alcohol-indulgent diving club his hope for a sparkling campus life is thrown into chaos.",
        poster_path: "/iZGnDnstcdorT0zJRpWzSQlMNz6.jpg",
        media_type: "movie",
        genre_ids: [35],
        popularity: 13.935,
        release_date: "2020-08-07",
        video: false,
        vote_average: 6,
        vote_count: 12,
      },
      {
        adult: false,
        backdrop_path: "/iNpbnWI2vQWGdPC9Pbt1RnV71R5.jpg",
        id: 91414,
        name: "Runway 24",
        original_language: "ja",
        original_name: "ランウェイ 24",
        overview:
          "Inoue Momoko admires her late father, who was a pilot. She begins work as a co-pilot at a low-cost airline. Under Captain Shinkai Kohei’s instructions, who knew her father, Inoue Momoko works hard to become a captain and her boyfriend Umino Daisuke supports her dream too.\n\nOne day, Inoue Momoko has a problem with a passenger complaining about the limit for carry-on baggage. At that time, Katsuki Tetsuya looks at the situation.",
        poster_path: "/2j2p3MF2GpSMHAFaYTgIRQeVOHa.jpg",
        media_type: "tv",
        genre_ids: [10751, 18],
        popularity: 7.628,
        first_air_date: "2019-07-06",
        vote_average: 6.7,
        vote_count: 3,
        origin_country: ["JP"],
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 974169,
    known_for_department: "Acting",
    name: "Jenna Ortega",
    original_name: "Jenna Ortega",
    popularity: 130.631,
    profile_path: "/7oUAtVgZU0uLdUSvDHKkINt1y7Y.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
        id: 119051,
        name: "Wednesday",
        original_language: "en",
        original_name: "Wednesday",
        overview:
          "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
        poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
        media_type: "tv",
        genre_ids: [10765, 9648, 35],
        popularity: 417.109,
        first_air_date: "2022-11-23",
        vote_average: 8.523,
        vote_count: 7768,
        origin_country: ["US"],
      },
      {
        adult: false,
        backdrop_path: "/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
        id: 646385,
        title: "Scream",
        original_language: "en",
        original_title: "Scream",
        overview:
          "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
        poster_path: "/971Kqs1q4nuSc9arn1QAuKYbfxy.jpg",
        media_type: "movie",
        genre_ids: [27, 9648, 53],
        popularity: 81.454,
        release_date: "2022-01-12",
        video: false,
        vote_average: 6.697,
        vote_count: 2899,
      },
      {
        adult: false,
        backdrop_path: "/70Rm9ItxKuEKN8iu6rNjfwAYUCJ.jpg",
        id: 760104,
        title: "X",
        original_language: "en",
        original_title: "X",
        overview:
          "In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives.",
        poster_path: "/woTQx9Q4b8aO13jR9dsj8C9JESy.jpg",
        media_type: "movie",
        genre_ids: [27, 53, 9648],
        popularity: 130.311,
        release_date: "2022-03-17",
        video: false,
        vote_average: 6.8,
        vote_count: 2449,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 106731,
    known_for_department: "Acting",
    name: "Nicolette Scorsese",
    original_name: "Nicolette Scorsese",
    popularity: 127.326,
    profile_path: "/i0PWIBj2dZQm76uepLhMO1188HS.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/1KYDPOC6ENDWCkW3TGCdca104hi.jpg",
        id: 5825,
        title: "National Lampoon's Christmas Vacation",
        original_language: "en",
        original_title: "National Lampoon's Christmas Vacation",
        overview:
          "It's Christmastime, and the Griswolds are preparing for a family seasonal celebration. But things never run smoothly for Clark, his wife Ellen, and their two kids. Clark's continual bad luck is worsened by his obnoxious family guests, but he manages to keep going, knowing that his Christmas bonus is due soon.",
        poster_path: "/gL8ZDtAy8vO95aAnv1H5CR4CGMA.jpg",
        media_type: "movie",
        genre_ids: [35],
        popularity: 111.889,
        release_date: "1989-11-30",
        video: false,
        vote_average: 7.226,
        vote_count: 2141,
      },
      {
        adult: false,
        backdrop_path: "/iiOfrrE9fwCrhmo8o5acrNJb5I7.jpg",
        id: 18215,
        title: "Boxing Helena",
        original_language: "en",
        original_title: "Boxing Helena",
        overview:
          "A top surgeon is besotted with a beautiful woman who once rebuffed him. Unable to come to terms with life without her, he tries to convince her that they need each other. She has other ideas, but a horrific accident leaves her at his mercy.",
        poster_path: "/fL8b32TY3Cxe661kztmzz5AlIM0.jpg",
        media_type: "movie",
        genre_ids: [18, 10749, 53, 27],
        popularity: 21.824,
        release_date: "1993-03-22",
        video: false,
        vote_average: 5.2,
        vote_count: 206,
      },
      {
        adult: false,
        backdrop_path: "/iARhC0Tor1XF0ADsCTvf0DEu3ZK.jpg",
        id: 41872,
        title: "Girls in Prison",
        original_language: "en",
        original_title: "Girls in Prison",
        overview:
          'Framed for the murder of a record company president in 1952 Hollywood, young, aspiring singer Aggie O\'Hanlon is sentenced to life in prison and tries to adjust to her life life behind bars in a hellish womens prison where she is befriended by other "lifer" inmates who help her out when Aggie finds herself marked for murder by an unknown source who thinks she knows more about the murder than she does.',
        poster_path: "/42gZLRZStmVH3shTSTj3iDZ9RBf.jpg",
        media_type: "movie",
        genre_ids: [80, 18, 53],
        popularity: 13.072,
        release_date: "1994-08-19",
        video: false,
        vote_average: 4.5,
        vote_count: 11,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 115440,
    known_for_department: "Acting",
    name: "Sydney Sweeney",
    original_name: "Sydney Sweeney",
    popularity: 121.927,
    profile_path: "/afr2eoktU4lFYtmtfKo05EbQdXo.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/oKt4J3TFjWirVwBqoHyIvv5IImd.jpg",
        id: 85552,
        name: "Euphoria",
        original_language: "en",
        original_name: "Euphoria",
        overview:
          "A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.",
        poster_path: "/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg",
        media_type: "tv",
        genre_ids: [18],
        popularity: 212.456,
        first_air_date: "2019-06-16",
        vote_average: 8.346,
        vote_count: 9143,
        origin_country: ["US"],
      },
      {
        adult: false,
        backdrop_path: "/3rwszCm4XyBtIWSjbUbgNwJOidu.jpg",
        id: 645710,
        title: "The Voyeurs",
        original_language: "en",
        original_title: "The Voyeurs",
        overview:
          "When Pippa and Thomas move into their dream apartment, they notice that their windows look directly into the apartment opposite – inviting them to witness the volatile relationship of the attractive couple across the street. But what starts as a simple curiosity turns into full-blown obsession with increasingly dangerous consequences.",
        poster_path: "/8Y4XOIWhpOvSOEn8XrxbkH9yAXO.jpg",
        media_type: "movie",
        genre_ids: [53],
        popularity: 44.008,
        release_date: "2021-08-25",
        video: false,
        vote_average: 6.663,
        vote_count: 711,
      },
      {
        adult: false,
        backdrop_path: "/oRiUKwDpcqDdoLwPoA4FIRh3hqY.jpg",
        id: 466272,
        title: "Once Upon a Time… in Hollywood",
        original_language: "en",
        original_title: "Once Upon a Time… in Hollywood",
        overview:
          "Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…",
        poster_path: "/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
        media_type: "movie",
        genre_ids: [35, 18, 53],
        popularity: 79.195,
        release_date: "2019-07-24",
        video: false,
        vote_average: 7.44,
        vote_count: 12427,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 85034,
    known_for_department: "Acting",
    name: "Ranbir Kapoor",
    original_name: "Ranbir Kapoor",
    popularity: 120.342,
    profile_path: "/ymYNHV9luwgyrw17NXHqbOWTQkg.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/lnNEmbGoxcSoO69NeavliNUxT3O.jpg",
        id: 127501,
        title: "Barfi!",
        original_language: "hi",
        original_title: "बर्फी!",
        overview:
          "Three young people learn that love can neither be defined nor contained by society's definition of normal and abnormal.",
        poster_path: "/8lVuWmArvr41CvyvpgI3elD5iB1.jpg",
        media_type: "movie",
        genre_ids: [18, 10749, 35],
        popularity: 20.588,
        release_date: "2012-09-13",
        video: false,
        vote_average: 7.497,
        vote_count: 294,
      },
      {
        adult: false,
        backdrop_path: "/Wi9bgiwfJPYKFcJIiUqCNDFNtf.jpg",
        id: 185008,
        title: "Yeh Jawaani Hai Deewani",
        original_language: "hi",
        original_title: "ये जवानी है दीवानी",
        overview:
          "Bunny and Naina meet when they graduate from college and again in their late 20s.",
        poster_path: "/em39H81XLCDgXsI7V4IcBZseEO6.jpg",
        media_type: "movie",
        genre_ids: [10749, 35],
        popularity: 26.54,
        release_date: "2013-05-31",
        video: false,
        vote_average: 7.256,
        vote_count: 238,
      },
      {
        adult: false,
        backdrop_path: "/YmrlTsqhmFsWo50QawaKTHOql7.jpg",
        id: 393445,
        title: "Ae Dil Hai Mushkil",
        original_language: "hi",
        original_title: "ऐ दिल है मुश्किल",
        overview:
          "Ayan falls in love with his soulmate, Alizeh, but she doesn’t reciprocate the feeling. Later, a relationship with Saba helps him realize Alizeh’s value in his life, irrespective of their relationship status.",
        poster_path: "/1BDnQBOIUsPFnlLw35gManvHKUs.jpg",
        media_type: "movie",
        genre_ids: [10749, 18],
        popularity: 33.282,
        release_date: "2016-10-27",
        video: false,
        vote_average: 6.402,
        vote_count: 183,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 976,
    known_for_department: "Acting",
    name: "Jason Statham",
    original_name: "Jason Statham",
    popularity: 119.223,
    profile_path: "/whNwkEQYWLFJA8ij0WyOOAD5xhQ.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/ysKahAEPP8h6MInuLjr0xuZOTjh.jpg",
        id: 107,
        title: "Snatch",
        original_language: "en",
        original_title: "Snatch",
        overview:
          "Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.",
        poster_path: "/56mOJth6DJ6JhgoE2jtpilVqJO.jpg",
        media_type: "movie",
        genre_ids: [80, 35],
        popularity: 47.807,
        release_date: "2000-09-01",
        video: false,
        vote_average: 7.806,
        vote_count: 8439,
      },
      {
        adult: false,
        backdrop_path: "/iP1cjN3ZGs1yJXROKaUj9hi1yF2.jpg",
        id: 345940,
        title: "The Meg",
        original_language: "en",
        original_title: "The Meg",
        overview:
          "A deep sea submersible pilot revisits his past fears in the Mariana Trench, and accidentally unleashes the seventy foot ancestor of the Great White Shark believed to be extinct.",
        poster_path: "/eyWICPcxOuTcDDDbTMOZawoOn8d.jpg",
        media_type: "movie",
        genre_ids: [28, 878, 27],
        popularity: 96.703,
        release_date: "2018-08-09",
        video: false,
        vote_average: 6.255,
        vote_count: 7173,
      },
      {
        adult: false,
        backdrop_path: "/kWt1OcPgwO1ssu57wgTKmq38JYw.jpg",
        id: 4108,
        title: "The Transporter",
        original_language: "en",
        original_title: "The Transporter",
        overview:
          "Former Special Forces officer, Frank Martin will deliver anything to anyone for the right price, and his no-questions-asked policy puts him in high demand. But when he realizes his latest cargo is alive, it sets in motion a dangerous chain of events. The bound and gagged Lai is being smuggled to France by a shady American businessman, and Frank works to save her as his own illegal activities are uncovered by a French detective.",
        poster_path: "/v3QIFUWgtVN4wejVuDZowuyJ20W.jpg",
        media_type: "movie",
        genre_ids: [28, 80, 53],
        popularity: 46.617,
        release_date: "2002-10-02",
        video: false,
        vote_average: 6.697,
        vote_count: 4982,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 1232179,
    known_for_department: "Acting",
    name: "Anna Slotky",
    original_name: "Anna Slotky",
    popularity: 118.62,
    profile_path: "/6NvXc8Z8t8rccjliVPparVeUGj0.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/pnkcE3Q3fPNM9XzWEN1gJJRYYX4.jpg",
        id: 772,
        title: "Home Alone 2: Lost in New York",
        original_language: "en",
        original_title: "Home Alone 2: Lost in New York",
        overview:
          "Instead of flying to Florida with his folks, Kevin ends up alone in New York, where he gets a hotel room with his dad's credit card—despite problems from a clerk and meddling bellboy. But when Kevin runs into his old nemeses, the Wet Bandits, he's determined to foil their plans to rob a toy store on Christmas Eve.",
        poster_path: "/uuitWHpJwxD1wruFl2nZHIb4UGN.jpg",
        media_type: "movie",
        genre_ids: [35, 10751, 12],
        popularity: 239.092,
        release_date: "1992-11-19",
        video: false,
        vote_average: 6.715,
        vote_count: 8851,
      },
      {
        adult: false,
        backdrop_path: "/bCFhGBYSLFSVdZmBZ6sENhMmi2Z.jpg",
        id: 771,
        title: "Home Alone",
        original_language: "en",
        original_title: "Home Alone",
        overview:
          "Eight-year-old Kevin McCallister makes the most of the situation after his family unwittingly leaves him behind when they go on Christmas vacation. But when a pair of bungling burglars set their sights on Kevin's house, the plucky kid stands ready to defend his territory. By planting booby traps galore, adorably mischievous Kevin stands his ground as his frantic mother attempts to race home before Christmas Day.",
        poster_path: "/9wSbe4CwObACCQvaUVhWQyLR5Vz.jpg",
        media_type: "movie",
        genre_ids: [35, 10751],
        popularity: 14.373,
        release_date: "1990-11-16",
        video: false,
        vote_average: 7.416,
        vote_count: 10352,
      },
      {
        adult: false,
        backdrop_path: "/eZmgVaSzSYBCw1pIX1yNetEjzc0.jpg",
        id: 155,
        name: "3rd Rock from the Sun",
        original_language: "en",
        original_name: "3rd Rock from the Sun",
        overview:
          "3rd Rock from the Sun is an American sitcom that aired from 1996 to 2001 on NBC. The show is about four extraterrestrials who are on an expedition to Earth, which they consider to be a very insignificant planet. The extraterrestrials pose as a human family in order to observe the behavior of human beings.",
        poster_path: "/sUB4lZghNnwQywKqgjIfJsyBqI2.jpg",
        media_type: "tv",
        genre_ids: [10751, 10765, 35, 18],
        popularity: 452.57,
        first_air_date: "1996-01-09",
        vote_average: 7.498,
        vote_count: 429,
        origin_country: ["US"],
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 1878952,
    known_for_department: "Acting",
    name: "Song Kang",
    original_name: "Song Kang",
    popularity: 115.358,
    profile_path: "/dMUXkMfkTEw3qrJisk0mQCQxmBI.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/mceCXNTny6a5F3rQgShLoyARw4l.jpg",
        id: 96648,
        name: "Sweet Home",
        original_language: "ko",
        original_name: "스위트홈",
        overview:
          "As humans turn into savage monsters and the world plunges into terror, a handful of survivors fight for their lives — and to hold on to their humanity.",
        poster_path: "/u8sLAJUvY9yzWqtVfKRQz5yin3D.jpg",
        media_type: "tv",
        genre_ids: [18, 10765, 80],
        popularity: 658.38,
        first_air_date: "2020-12-18",
        vote_average: 8.4,
        vote_count: 1156,
        origin_country: ["KR"],
      },
      {
        adult: false,
        backdrop_path: "/mXouvrZbn8YpZMURGvw30QK8qfo.jpg",
        id: 89641,
        name: "Love Alarm",
        original_language: "ko",
        original_name: "좋아하면 울리는",
        overview:
          "Love Alarm is an app that tells you if someone within a 10-meter radius has a crush on you. It quickly becomes a social phenomenon. While everyone talks about it and uses it to test their love and popularity, Jojo is one of the few people who have yet to download the app. However, she soon faces a love triangle situation between Sun-oh whom she starts to have feelings for, and Hye-young, who has had a huge crush on her.",
        poster_path: "/s87JyAWtRLLlmsYWXTED1l8henB.jpg",
        media_type: "tv",
        genre_ids: [18, 10765],
        popularity: 38.727,
        first_air_date: "2019-08-22",
        vote_average: 8.402,
        vote_count: 1861,
        origin_country: ["KR"],
      },
      {
        adult: false,
        backdrop_path: "/iSAH9nH10hke3IW9woUSnTmSHm4.jpg",
        id: 119464,
        name: "Navillera",
        original_language: "ko",
        original_name: "나빌레라",
        overview:
          "A 70-year-old with a dream and a 23-year-old with a gift lift each other out of harsh realities and rise to the challenge of becoming ballerinos.",
        poster_path: "/pBd6pEhszsWk95TrUqo4bdXhH8T.jpg",
        media_type: "tv",
        genre_ids: [18],
        popularity: 23.783,
        first_air_date: "2021-03-22",
        vote_average: 8.6,
        vote_count: 168,
        origin_country: ["KR"],
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 27972,
    known_for_department: "Acting",
    name: "Josh Hutcherson",
    original_name: "Josh Hutcherson",
    popularity: 114.327,
    profile_path: "/npowygg8rH7uJ4v7rAoDMsHBhNq.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/yDbyVT8tTOgXUrUXNkHEUqbxb1K.jpg",
        id: 70160,
        title: "The Hunger Games",
        original_language: "en",
        original_title: "The Hunger Games",
        overview:
          "Every year in the ruins of what was once North America, the nation of Panem forces each of its twelve districts to send a teenage boy and girl to compete in the Hunger Games.  Part twisted entertainment, part government intimidation tactic, the Hunger Games are a nationally televised event in which “Tributes” must fight with one another until one survivor remains.  Pitted against highly-trained Tributes who have prepared for these Games their entire lives, Katniss is forced to rely upon her sharp instincts as well as the mentorship of drunken former victor Haymitch Abernathy.  If she’s ever to return home to District 12, Katniss must make impossible choices in the arena that weigh survival against humanity and life against love. The world will be watching.",
        poster_path: "/yXCbOiVDCxO71zI7cuwBRXdftq8.jpg",
        media_type: "movie",
        genre_ids: [878, 12, 14],
        popularity: 78.889,
        release_date: "2012-03-12",
        video: false,
        vote_average: 7.2,
        vote_count: 20933,
      },
      {
        adult: false,
        backdrop_path: "/oDYQhS5LtFXUP0x6bCZije5HRr9.jpg",
        id: 101299,
        title: "The Hunger Games: Catching Fire",
        original_language: "en",
        original_title: "The Hunger Games: Catching Fire",
        overview:
          'Katniss Everdeen has returned home safe after winning the 74th Annual Hunger Games along with fellow tribute Peeta Mellark. Winning means that they must turn around and leave their family and close friends, embarking on a "Victor\'s Tour" of the districts. Along the way Katniss senses that a rebellion is simmering, but the Capitol is still very much in control as President Snow prepares the 75th Annual Hunger Games (The Quarter Quell) - a competition that could change Panem forever.',
        poster_path: "/vrQHDXjVmbYzadOXQ0UaObunoy2.jpg",
        media_type: "movie",
        genre_ids: [12, 28, 878],
        popularity: 144.493,
        release_date: "2013-11-15",
        video: false,
        vote_average: 7.425,
        vote_count: 16439,
      },
      {
        adult: false,
        backdrop_path: "/tFlSDoWQsAZ2qjICKzfP5Yw6zM5.jpg",
        id: 131631,
        title: "The Hunger Games: Mockingjay - Part 1",
        original_language: "en",
        original_title: "The Hunger Games: Mockingjay - Part 1",
        overview:
          "Katniss Everdeen reluctantly becomes the symbol of a mass rebellion against the autocratic Capitol.",
        poster_path: "/4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg",
        media_type: "movie",
        genre_ids: [878, 12, 53],
        popularity: 216.727,
        release_date: "2014-11-19",
        video: false,
        vote_average: 6.803,
        vote_count: 14972,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 1190668,
    known_for_department: "Acting",
    name: "Timothée Chalamet",
    original_name: "Timothée Chalamet",
    popularity: 112.04,
    profile_path: "/BE2sdjpgsa2rNTFa66f7upkaOP.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/zvOJawrnmgK0sL293mOXOdLvTXQ.jpg",
        id: 398818,
        title: "Call Me by Your Name",
        original_language: "en",
        original_title: "Call Me by Your Name",
        overview:
          "In 1980s Italy, a relationship begins between seventeen-year-old teenage Elio and the older adult man hired as his father's research assistant.",
        poster_path: "/mZ4gBdfkhP9tvLH1DO4m4HYtiyi.jpg",
        media_type: "movie",
        genre_ids: [10749, 18],
        popularity: 71.768,
        release_date: "2017-09-01",
        video: false,
        vote_average: 8.2,
        vote_count: 11464,
      },
      {
        adult: false,
        backdrop_path: "/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
        id: 438631,
        title: "Dune",
        original_language: "en",
        original_title: "Dune",
        overview:
          "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
        poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
        media_type: "movie",
        genre_ids: [878, 12],
        popularity: 125.189,
        release_date: "2021-09-15",
        video: false,
        vote_average: 7.786,
        vote_count: 9681,
      },
      {
        adult: false,
        backdrop_path: "/urwWVsciRiNSmhtMJcck0noWAXr.jpg",
        id: 504949,
        title: "The King",
        original_language: "en",
        original_title: "The King",
        overview:
          "England, 15th century. Hal, a capricious prince who lives among the populace far from court, is forced by circumstances to reluctantly accept the throne and become Henry V.",
        poster_path: "/8u0QBGUbZcBW59VEAdmeFl9g98N.jpg",
        media_type: "movie",
        genre_ids: [18, 36, 10752],
        popularity: 37.797,
        release_date: "2019-10-11",
        video: false,
        vote_average: 7.152,
        vote_count: 2966,
      },
    ],
  },
  {
    adult: false,
    gender: 0,
    id: 3234630,
    known_for_department: "Acting",
    name: "Sangeeth Shobhan",
    original_name: "Sangeeth Shobhan",
    popularity: 104.233,
    profile_path: "/7Vox31bH7XmgPNJzMKGa4uGyjW8.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/jBnnkkXRZ0pV3Tw31Z2ALO638wA.jpg",
        id: 1187075,
        title: "MAD",
        original_language: "te",
        original_title: "MAD",
        overview:
          "Set in an engineering college and revolves around the antics of the students there, primarily the boys, who get a kick out of torturing the hostel warden.",
        poster_path: "/nDpOmgBfQZwOpFBcgokQGqd74r1.jpg",
        media_type: "movie",
        genre_ids: [35, 10749, 18],
        popularity: 2.816,
        release_date: "2023-10-06",
        video: false,
        vote_average: 7,
        vote_count: 4,
      },
      {
        adult: false,
        backdrop_path: "/1jof3bGVg67HLmvRHfTzqb2IODO.jpg",
        id: 138179,
        name: "Oka Chinna Family Story",
        original_language: "te",
        original_name: "ఒక చిన్న Family Story",
        overview:
          "Mahesh and his mother embark on an adventurous journey filled with hilarious situations as they try to make quick money to repay a huge loan.",
        poster_path: "/u1Tq2Qqb1oUJ6WSzVJqWk03LzEl.jpg",
        media_type: "tv",
        genre_ids: [35, 10751],
        popularity: 5.927,
        first_air_date: "2021-11-19",
        vote_average: 7.5,
        vote_count: 2,
        origin_country: ["IN"],
      },
      {
        adult: false,
        backdrop_path: "/d7jfcyPb5ZncLyhPFNjpuIeeZ1y.jpg",
        id: 1119091,
        title: "Prema Vimanam",
        original_language: "te",
        original_title: "ప్రేమ విమానం",
        overview:
          "Two kids with a dream to board a flight cross paths with a young couple who must urgently catch the flight to start a new life.",
        poster_path: "/9eljOANAd6HafUDdmp3xnmkpnt8.jpg",
        media_type: "movie",
        genre_ids: [18, 35],
        popularity: 2.573,
        release_date: "2023-10-13",
        video: false,
        vote_average: 7,
        vote_count: 1,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 1548301,
    known_for_department: "Acting",
    name: "Farrah Mackenzie",
    original_name: "Farrah Mackenzie",
    popularity: 104.068,
    profile_path: "/6IOdWe5J3AsPVomDTcVDUcY1c6z.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/d3Y9L11tgnYIKhAaRWfbaKGCjcM.jpg",
        id: 399170,
        title: "Logan Lucky",
        original_language: "en",
        original_title: "Logan Lucky",
        overview:
          "Trying to reverse a family curse, brothers Jimmy and Clyde Logan set out to execute an elaborate robbery during the legendary Coca-Cola 600 race at the Charlotte Motor Speedway.",
        poster_path: "/mQrhrBaaHvRfBQq0Px3HtVbH9iE.jpg",
        media_type: "movie",
        genre_ids: [35, 80, 28, 18],
        popularity: 36.323,
        release_date: "2017-08-17",
        video: false,
        vote_average: 6.73,
        vote_count: 3265,
      },
      {
        adult: false,
        backdrop_path: "/alsTIqT2ApBUUs8zEZEpmw1kDEa.jpg",
        id: 412105,
        title: "You Get Me",
        original_language: "en",
        original_title: "You Get Me",
        overview:
          "After arguing with his girlfriend, Ali, Tyler lands in the arms of sexy new girl, Holly. The next morning, he finds that not only does Ali agree to take him back, but Holly is a new student at their school and is dead set on her new man.",
        poster_path: "/5eV0mIQqSztD3McjO22EOFlQDj1.jpg",
        media_type: "movie",
        genre_ids: [53, 10749, 18],
        popularity: 43.371,
        release_date: "2017-06-19",
        video: false,
        vote_average: 5.625,
        vote_count: 1643,
      },
      {
        adult: false,
        backdrop_path: "/z6OkT7XjzSrgstiTlld0jUvME9y.jpg",
        id: 726209,
        title: "Leave the World Behind",
        original_language: "en",
        original_title: "Leave the World Behind",
        overview:
          "A family's getaway to a luxurious rental home takes an ominous turn when a cyberattack knocks out their devices — and two strangers appear at their door.",
        poster_path: "/29rhl1xopxA7JlGVVsf1UHfYPvN.jpg",
        media_type: "movie",
        genre_ids: [18, 9648, 53, 878],
        popularity: 731.384,
        release_date: "2023-11-22",
        video: false,
        vote_average: 6.676,
        vote_count: 532,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 224513,
    known_for_department: "Acting",
    name: "Ana de Armas",
    original_name: "Ana de Armas",
    popularity: 98.27,
    profile_path: "/3vxvsmYLTf4jnr163SUlBIw51ee.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/ilRyazdMJwN05exqhwK4tMKBYZs.jpg",
        id: 335984,
        title: "Blade Runner 2049",
        original_language: "en",
        original_title: "Blade Runner 2049",
        overview:
          "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
        poster_path: "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
        media_type: "movie",
        genre_ids: [878, 18],
        popularity: 99.282,
        release_date: "2017-10-04",
        video: false,
        vote_average: 7.55,
        vote_count: 12580,
      },
      {
        adult: false,
        backdrop_path: "/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg",
        id: 546554,
        title: "Knives Out",
        original_language: "en",
        original_title: "Knives Out",
        overview:
          "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
        poster_path: "/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
        media_type: "movie",
        genre_ids: [35, 80, 9648],
        popularity: 62.823,
        release_date: "2019-11-27",
        video: false,
        vote_average: 7.845,
        vote_count: 11361,
      },
      {
        adult: false,
        backdrop_path: "/3Mnbw4gOYz5BNZB9PhZ2cyBSQum.jpg",
        id: 308266,
        title: "War Dogs",
        original_language: "en",
        original_title: "War Dogs",
        overview:
          "Based on the true story of two young men, David Packouz and Efraim Diveroli, who won a $300 million contract from the Pentagon to arm America's allies in Afghanistan.",
        poster_path: "/uH9qGH5XS1iZXCSb3tgu40dxQoh.jpg",
        media_type: "movie",
        genre_ids: [35, 80, 18],
        popularity: 35.644,
        release_date: "2016-08-18",
        video: false,
        vote_average: 6.908,
        vote_count: 4572,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 932967,
    known_for_department: "Acting",
    name: "Mahershala Ali",
    original_name: "Mahershala Ali",
    popularity: 97.383,
    profile_path: "/9ZmSejm5lnUVY5IJ1iNx2QEjnHb.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/5En0fmDagt3Pk8d7P3uTwfeQceg.jpg",
        id: 490132,
        title: "Green Book",
        original_language: "en",
        original_title: "Green Book",
        overview:
          "Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.",
        poster_path: "/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg",
        media_type: "movie",
        genre_ids: [18, 36],
        popularity: 74.595,
        release_date: "2018-11-16",
        video: false,
        vote_average: 8.244,
        vote_count: 10717,
      },
      {
        adult: false,
        backdrop_path: "/qGQf2OHIkoh89K8XeKQzhxczf96.jpg",
        id: 324857,
        title: "Spider-Man: Into the Spider-Verse",
        original_language: "en",
        original_title: "Spider-Man: Into the Spider-Verse",
        overview:
          'Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson "Kingpin" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.',
        poster_path: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
        media_type: "movie",
        genre_ids: [28, 12, 16, 878],
        popularity: 110.467,
        release_date: "2018-12-06",
        video: false,
        vote_average: 8.406,
        vote_count: 14322,
      },
      {
        adult: false,
        backdrop_path: "/8RKBHHRqOMOLh5qW3sS6TSFTd8h.jpg",
        id: 399579,
        title: "Alita: Battle Angel",
        original_language: "en",
        original_title: "Alita: Battle Angel",
        overview:
          "When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past.",
        poster_path: "/xRWht48C2V8XNfzvPehyClOvDni.jpg",
        media_type: "movie",
        genre_ids: [28, 878, 12],
        popularity: 85.574,
        release_date: "2019-01-31",
        video: false,
        vote_average: 7.224,
        vote_count: 8573,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 64,
    known_for_department: "Acting",
    name: "Gary Oldman",
    original_name: "Gary Oldman",
    popularity: 93.895,
    profile_path: "/hHP0769L7YrApkMKCOyb9cwgxBW.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
        id: 155,
        title: "The Dark Knight",
        original_language: "en",
        original_title: "The Dark Knight",
        overview:
          "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
        poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        media_type: "movie",
        genre_ids: [18, 28, 80, 53],
        popularity: 119.952,
        release_date: "2008-07-16",
        video: false,
        vote_average: 8.513,
        vote_count: 31040,
      },
      {
        adult: false,
        backdrop_path: "/c3OHQncTAnKFhdOTX7D3LTW6son.jpg",
        id: 49026,
        title: "The Dark Knight Rises",
        original_language: "en",
        original_title: "The Dark Knight Rises",
        overview:
          "Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
        poster_path: "/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg",
        media_type: "movie",
        genre_ids: [28, 80, 18, 53],
        popularity: 94.872,
        release_date: "2012-07-17",
        video: false,
        vote_average: 7.777,
        vote_count: 21586,
      },
      {
        adult: false,
        backdrop_path: "/zXwFJMwvQcJFitP9GcHZvHAHGe8.jpg",
        id: 399404,
        title: "Darkest Hour",
        original_language: "en",
        original_title: "Darkest Hour",
        overview:
          "In May 1940, the fate of World War II hangs on Winston Churchill, who must decide whether to negotiate with Adolf Hitler or fight on knowing that it could mean the end of the British Empire.",
        poster_path: "/xa6G3aKlysQeVg9wOb0dRcIGlWu.jpg",
        media_type: "movie",
        genre_ids: [18, 36],
        popularity: 52.021,
        release_date: "2017-11-22",
        video: false,
        vote_average: 7.353,
        vote_count: 4820,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 1613836,
    known_for_department: "Acting",
    name: "Rowoon",
    original_name: "Rowoon",
    popularity: 88.478,
    profile_path: "/sOTYcl8SGmtxpWq0EQKJhX8dztr.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/2lQ1PwGFZKM9EakCw1j4NShEuuj.jpg",
        id: 136369,
        name: "Tomorrow",
        original_language: "ko",
        original_name: "내일",
        overview:
          "Made half-human and half-spirit by accident, a young man is employed by a company of grim reapers in the underworld to carry out special missions.",
        poster_path: "/7pOC2Wr6aavn6OPkFJ9YqhCV5hW.jpg",
        media_type: "tv",
        genre_ids: [18, 10765, 10759],
        popularity: 29.484,
        first_air_date: "2022-04-01",
        vote_average: 8.561,
        vote_count: 155,
        origin_country: ["KR"],
      },
      {
        adult: false,
        backdrop_path: "/4r7scgI5aUrShN0YzriAatWd15e.jpg",
        id: 129478,
        name: "The King's Affection",
        original_language: "ko",
        original_name: "연모",
        overview:
          "When the crown prince is killed, his twin sister assumes the throne while trying to keep her identity and affection for her first love a royal secret.",
        poster_path: "/mcfX0IqWibPhF5H4i2Q5gUlwwxk.jpg",
        media_type: "tv",
        genre_ids: [18],
        popularity: 85.061,
        first_air_date: "2021-10-11",
        vote_average: 8.3,
        vote_count: 239,
        origin_country: ["KR"],
      },
      {
        adult: false,
        backdrop_path: "/jJMfTkvU2exHwCFoBHsIqwaHImh.jpg",
        id: 215001,
        name: "Destined with You",
        original_language: "ko",
        original_name: "이 연애는 불가항력",
        overview:
          "A lawyer bound by a centuries-old curse becomes entangled with a civil servant who holds the key to his freedom — igniting an unexpected romance.",
        poster_path: "/fMiLKTIFB7YCBQSYoTJ7NCrPcD6.jpg",
        media_type: "tv",
        genre_ids: [18, 10765, 35],
        popularity: 159.073,
        first_air_date: "2023-08-23",
        vote_average: 7.967,
        vote_count: 75,
        origin_country: ["KR"],
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 2502703,
    known_for_department: "Acting",
    name: "Alyson Gorske",
    original_name: "Alyson Gorske",
    popularity: 87.946,
    profile_path: "/aqohlkcnI9yZdRmgDWjipCncmh8.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/9fWW38bLEdofv77bUPLIu8zLN6.jpg",
        id: 844636,
        title: "Jungle Run",
        original_language: "en",
        original_title: "Jungle Run",
        overview:
          "A brother and sister's journey into the jungle to find their missing father.",
        poster_path: "/7qz8G0DcgLUkJSbLU5YpzQYlOnb.jpg",
        media_type: "movie",
        genre_ids: [12, 28],
        popularity: 24.525,
        release_date: "2021-06-24",
        video: false,
        vote_average: 6.1,
        vote_count: 99,
      },
      {
        adult: false,
        backdrop_path: "/c8XIFuJCPTtTJdSRpqnUoMr6eK1.jpg",
        id: 667574,
        title: "Battle Star Wars",
        original_language: "en",
        original_title: "Battle Star Wars",
        overview:
          "When the leader of the evil Coalition threatens to destroy a Rebel planet for its resources, his daughter will have no choice but to join the Rebel side and fight for what is right.",
        poster_path: "/ocA0ECiFoB4d1HITyEDQlLk7x84.jpg",
        media_type: "movie",
        genre_ids: [878, 28],
        popularity: 18.03,
        release_date: "2020-01-28",
        video: false,
        vote_average: 5.135,
        vote_count: 37,
      },
      {
        adult: false,
        backdrop_path: "/aDQBgiWx2hLwKXbPrc92ILoO5LP.jpg",
        id: 1081353,
        title: "Amy's F**k It List",
        original_language: "en",
        original_title: "Amy's F**k It List",
        overview:
          "Plain and basic Amy receives news that suddenly turns her world upside down. Together with her outspoken and bold Sister Mary, the pair embark on a mission to set things right in the world and reconnect their once lost bond along the way.",
        poster_path: "/m4lFMnotILTWriXPoEhTIuVRNPr.jpg",
        media_type: "movie",
        genre_ids: [35],
        popularity: 11.458,
        release_date: "2023-02-04",
        video: false,
        vote_average: 5,
        vote_count: 5,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 192,
    known_for_department: "Acting",
    name: "Morgan Freeman",
    original_name: "Morgan Freeman",
    popularity: 86.397,
    profile_path: "/jPsLqiYGSofU4s6BjrxnefMfabb.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/dYjZ27hDw2QFaEIfzbNGwW0IkV9.jpg",
        id: 807,
        title: "Se7en",
        original_language: "en",
        original_title: "Se7en",
        overview:
          'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
        poster_path: "/6yoghtyTpznpBik8EngEmJskVUO.jpg",
        media_type: "movie",
        genre_ids: [80, 9648, 53],
        popularity: 94.55,
        release_date: "1995-09-22",
        video: false,
        vote_average: 8.371,
        vote_count: 19712,
      },
      {
        adult: false,
        backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
        id: 278,
        title: "The Shawshank Redemption",
        original_language: "en",
        original_title: "The Shawshank Redemption",
        overview:
          "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        media_type: "movie",
        genre_ids: [18, 80],
        popularity: 132.004,
        release_date: "1994-09-23",
        video: false,
        vote_average: 8.706,
        vote_count: 25092,
      },
      {
        adult: false,
        backdrop_path: "/ozVwXlfxqNsariipatGwa5px3Pm.jpg",
        id: 240832,
        title: "Lucy",
        original_language: "en",
        original_title: "Lucy",
        overview:
          "A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.",
        poster_path: "/dhjyfcwEoW6jJ4Q7DpZTp6E58GA.jpg",
        media_type: "movie",
        genre_ids: [28, 878],
        popularity: 69.144,
        release_date: "2014-07-25",
        video: false,
        vote_average: 6.443,
        vote_count: 15319,
      },
    ],
  },
];

export default actors;
